Filter bookmarks when searching filesystem versions.
zrepl/zrepl pull request #619
Opened 2022-07-18 08:14 UTC by kresike

Fixes #490

This is an old bug that I found and have been using this fix since. I've updated it to the newest version and seems to be working fine. @kpfleming please test it if you have the resources for it.

@problame please review.

2022-07-18 10:29 UTC, kpfleming commented
Thanks @kresike! I'll test this in the next few days.

2022-07-18 22:06 UTC, problame requested changes
Thanks for your contribution, @kresike !

2022-07-18 22:06 UTC, problame commented on replication/logic/diff/diff.go
> +	receiver = FilterBookmarksFromVersionList(receiver)
1. Naming: let's call this `StripBookmarksFromVersionList` 
2. Please add a comment to explain why we need to strip the bookmarks.

2022-07-18 22:06 UTC, problame commented on replication/logic/diff/diff.go
> +	fslice := make([]*FilesystemVersion, 0)
nit: you can use `make(..., 0, len(fsvslice))` to suggest a capacity while still keeping length at 0. Makes for fewer allocations.

2022-07-31 13:26 UTC, problame commented
I'm going to merge this, as it definitely fixes a problem, and I assume @kresike tested it on their side.

Added a comment, unit tests, and changelog entry.
Thanks for your contribution, @kresike

2022-07-31 13:33 UTC, merged