Add support of shell patterns for filesystems
zrepl/zrepl pull request #755
Opened 2023-10-21 17:26 UTC by dsh2dsh

Config like
```
filesystems:
  "zroot/jails</*/root": true
```
will include datasets `zroot/jails/a/root` and `zroot/jails/b/root`, but wont
include `zroot/jails/a` and `zroot/jails/b`.

2023-10-31 21:53 UTC, problame reviewed
The problem with wildcards is specificity, i.e., which rule to consider when multiple rules match. For example, take dataset `a/b/c/d` and rules `a/*/d` and `a/*/c/d`. Which rule is more specific? 

Also, did you think through what happens if there are multiple `*`  in one rule?


Also I think the

```
        "tank/bar</*/foo": true # rule 4
```

from the example looks quite weird.
Is there a reason why you only allow `*` for rules with `<`?

2023-11-02 22:06 UTC, dsh2dsh commented
> take dataset a/b/c/d and rules a/*/d and a/*/c/d. Which rule is more specific?

For one dataset one shell pattern rule possible. Somebody could add the same dataset twice with different shell patterns, but I think that's up to sysadmin, who is configuring zrepl.

> Also, did you think through what happens if there are multiple * in one rule?
It'll just works according to shell patterns: https://pkg.go.dev/path/filepath#Match

> from the example looks quite weird

Well, using of `<` in dataset looks same weird, but you use it. :)

> Is there a reason why you only allow * for rules with <?

Not sure I understand what do you mean. Shell patterns allow more symbols, see https://pkg.go.dev/path/filepath#Match

2023-12-10 12:01 UTC, InsanePrawn requested changes
Whoops, had this review stuck unsent for weeks.

2023-12-10 12:06 UTC, InsanePrawn commented
I remember also writing a comment referencing #601, seems like that got lost though.

2024-05-07 22:30 UTC, closed without merging